steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'gcr.io/${PROJECT_ID}/solana-options-frontend:${SHORT_SHA}',
        '-t',
        'gcr.io/${PROJECT_ID}/solana-options-frontend:latest',
        '.',
        '--build-arg',
        'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}',
        '--build-arg',
        'SHORT_SHA=${SHORT_SHA}',
      ]
    id: 'Build docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/solana-options-frontend:${SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/solana-options-frontend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        '${_DEPLOY_TARGET}',
        '--image',
        'gcr.io/${PROJECT_ID}/solana-options-frontend:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--update-env-vars=SHORT_SHA=${SHORT_SHA}',
        '--update-env-vars=TAG_NAME=${TAG_NAME}',
        '--update-env-vars=BRANCH_NAME=${BRANCH_NAME}',
      ]
